type subCategories = {
     subCategoryName: string;
     subSubCategories: string[];
};

export interface CategoriesDataType {
     category: string;
     subcategories: subCategories[];
}
export function addPrefixToDuplicates(dataArray: CategoriesDataType[]): CategoriesDataType[] {
     dataArray.forEach((data) => {
          const { subcategories } = data;

          subcategories.forEach((currentSubCategory, currentIndex) => {
               const { subCategoryName, subSubCategories } = currentSubCategory;

               subSubCategories.forEach((subSubCategory, subSubIndex) => {
                    // Check if the subSubCategory exists in other subCategories
                    const isDuplicate = subcategories.some(
                         (otherSubCategory, otherIndex) =>
                              otherIndex !== currentIndex && otherSubCategory.subSubCategories.includes(subSubCategory),
                    );

                    // If it's a duplicate, add the prefix
                    if (isDuplicate) {
                         subcategories[currentIndex].subSubCategories[
                              subSubIndex
                         ] = `${subCategoryName} ${subSubCategory}`;
                    }
               });
          });
     });

     return dataArray;
}
export const categories: CategoriesDataType[] = [
     {
          category: "Electronics",
          subcategories: [
               {
                    subCategoryName: "Mobile Phones",
                    subSubCategories: [
                         "Smartphones",
                         "Feature Phones",
                         "Gaming Phones",
                         "Camera Phones",
                         "Budget Phones",
                         "Refurbished Phones",
                         "Accessories",
                         "Bluetooth Headsets",
                         "Power Banks",
                         "Phone Cases",
                    ],
               },
               {
                    subCategoryName: "Laptops",
                    subSubCategories: [
                         "Gaming Laptops",
                         "UltraBooks",
                         "Business Laptops",
                         "2-in-1 Laptops",
                         "Chromebooks",
                         "MacBooks",
                         "Accessories",
                         "Laptop Bags",
                         "Laptop Chargers",
                         "Laptop Stands",
                    ],
               },
               {
                    subCategoryName: "Audio Devices",
                    subSubCategories: [
                         "Headphones",
                         "Speakers",
                         "Earbuds",
                         "Soundbars",
                         "Wireless Chargers",
                         "Microphones",
                         "Accessories",
                         "Bluetooth Speakers",
                         "Gaming Headsets",
                         "Home Audio Systems",
                    ],
               },
               {
                    subCategoryName: "Cameras",
                    subSubCategories: [
                         "Digital Cameras",
                         "Mirrorless Cameras",
                         "DSLR Cameras",
                         "Action Cameras",
                         "Instant Cameras",
                         "Camera Lenses",
                         "Accessories",
                         "Camera Bags",
                         "Tripods",
                         "Memory Cards",
                    ],
               },
               {
                    subCategoryName: "Wearables",
                    subSubCategories: [
                         "Smartwatches",
                         "Fitness Trackers",
                         "VR Headsets",
                         "Smart Glasses",
                         "Activity Monitors",
                         "Accessories",
                         "Sports Watches",
                         "Fitness Bands",
                         "VR Accessories",
                         "Charging Cables",
                    ],
               },
               {
                    subCategoryName: "Home Appliances",
                    subSubCategories: [
                         "Vacuum Cleaners",
                         "Air Purifiers",
                         "Coffee Makers",
                         "Blenders",
                         "Toasters",
                         "Microwaves",
                         "Accessories",
                         "Filters",
                         "Coffee Grinder",
                         "Replacement Parts",
                    ],
               },
               {
                    subCategoryName: "Gadgets and Accessories",
                    subSubCategories: [
                         "Smart Home Devices",
                         "Drones",
                         "External Hard Drives",
                         "USB Gadgets",
                         "Computer Peripherals",
                         "Cables and Adapters",
                         "Accessories",
                         "Smart Plugs",
                         "Wireless Mouse",
                         "USB Hubs",
                    ],
               },
               {
                    subCategoryName: "Gaming",
                    subSubCategories: [
                         "Gaming Consoles",
                         "Gaming Laptops",
                         "Gaming Desktops",
                         "Gaming Monitors",
                         "Gaming Accessories",
                         "Gaming Chairs",
                         "Games",
                         "Headsets",
                         "Controllers",
                         "Mousepads",
                    ],
               },
               {
                    subCategoryName: "Smart Home",
                    subSubCategories: [
                         "Smart Speakers",
                         "Smart Lights",
                         "Smart Thermostats",
                         "Smart Cameras",
                         "Smart Locks",
                         "Smart Plugs",
                         "Accessories",
                         "Hub Devices",
                         "Smart Sensors",
                         "Security Systems",
                    ],
               },
               {
                    subCategoryName: "Office Electronics",
                    subSubCategories: [
                         "Printers",
                         "Scanners",
                         "Projectors",
                         "Shredders",
                         "Calculators",
                         "Label Makers",
                         "Accessories",
                         "Printer Ink",
                         "Printer Paper",
                         "Laser Pointers",
                    ],
               },
          ],
     },
     {
          category: "Fashion",
          subcategories: [
               {
                    subCategoryName: "Men's Clothing",
                    subSubCategories: [
                         "T-Shirts",
                         "Jeans",
                         "Shirts",
                         "Sweaters",
                         "Jackets",
                         "Activewear",
                         "Accessories",
                         "Hats",
                         "Belts",
                         "Watches",
                    ],
               },
               {
                    subCategoryName: "Women's Clothing",
                    subSubCategories: [
                         "Dresses",
                         "Blouses",
                         "Pants",
                         "Skirts",
                         "Coats",
                         "Athleisure",
                         "Accessories",
                         "Scarves",
                         "Jewelry",
                         "Handbags",
                    ],
               },
               {
                    subCategoryName: "Accessories",
                    subSubCategories: [
                         "Hats",
                         "Scarves",
                         "Belts",
                         "Gloves",
                         "Sunglasses",
                         "Watches",
                         "Bags",
                         "Jewelry",
                         "Wallets",
                         "Ties",
                    ],
               },
               {
                    subCategoryName: "Footwear",
                    subSubCategories: [
                         "Sneakers",
                         "Boots",
                         "Sandals",
                         "Heels",
                         "Flats",
                         "Athletic Shoes",
                         "Slippers",
                         "Oxfords",
                         "Loafers",
                         "Espadrilles",
                    ],
               },
               {
                    subCategoryName: "Kids' Clothing",
                    subSubCategories: [
                         "Tops",
                         "Bottoms",
                         "Dresses",
                         "Outerwear",
                         "Sleepwear",
                         "Accessories",
                         "Shoes",
                         "Swimwear",
                         "School Uniforms",
                         "Socks",
                    ],
               },
               {
                    subCategoryName: "Intimates",
                    subSubCategories: [
                         "Bras",
                         "Panties",
                         "Lingerie Sets",
                         "Shapewear",
                         "Sleepwear",
                         "Robes",
                         "Thermal Wear",
                         "Socks",
                         "Hosiery",
                         "Slips",
                    ],
               },
               {
                    subCategoryName: "Swimwear",
                    subSubCategories: [
                         "Bikinis",
                         "One-Piece Swimsuits",
                         "Swim Trunks",
                         "Cover-Ups",
                         "Rash Guards",
                         "Board Shorts",
                         "Swim Accessories",
                         "Swim Dresses",
                         "Tankinis",
                         "Swim Tops",
                    ],
               },
               {
                    subCategoryName: "Maternity Clothing",
                    subSubCategories: [
                         "Tops",
                         "Bottoms",
                         "Dresses",
                         "Outerwear",
                         "Intimates",
                         "Activewear",
                         "Accessories",
                         "Nursing Bras",
                         "Pregnancy Pillows",
                         "Belly Bands",
                    ],
               },
               {
                    subCategoryName: "Athleisure",
                    subSubCategories: [
                         "Athletic Tops",
                         "Athletic Bottoms",
                         "Sports Bras",
                         "Athletic Shoes",
                         "Yoga Pants",
                         "Hoodies",
                         "Sweatpants",
                         "Running Jackets",
                         "Fitness Accessories",
                         "Compression Wear",
                    ],
               },
               {
                    subCategoryName: "Formal Wear",
                    subSubCategories: [
                         "Suits",
                         "Dresses",
                         "Tuxedos",
                         "Evening Gowns",
                         "Formal Shirts",
                         "Cocktail Dresses",
                         "Formal Shoes",
                         "Clutches",
                         "Ties",
                         "Cummerbunds",
                    ],
               },
          ],
     },
     {
          category: "Home and Garden",
          subcategories: [
               {
                    subCategoryName: "Furniture",
                    subSubCategories: [
                         "Living Room",
                         "Bedroom",
                         "Dining Room",
                         "Office",
                         "Outdoor",
                         "Kids' Furniture",
                         "Accent Furniture",
                         "Kitchen and Dining",
                         "Storage",
                         "Entryway",
                    ],
               },
               {
                    subCategoryName: "Bedding and Bath",
                    subSubCategories: [
                         "Bedding Sets",
                         "Bedspreads",
                         "Duvet Covers",
                         "Pillows",
                         "Towels",
                         "Shower Curtains",
                         "Bath Mats",
                         "Blankets",
                         "Quilts",
                         "Mattress Toppers",
                    ],
               },
               {
                    subCategoryName: "Home Decor",
                    subSubCategories: [
                         "Wall Art",
                         "Mirrors",
                         "Clocks",
                         "Candles",
                         "Vases",
                         "Decorative Pillows",
                         "Throws",
                         "Rugs",
                         "Indoor Plants",
                         "Decorative Accents",
                    ],
               },
               {
                    subCategoryName: "Kitchen and Dining",
                    subSubCategories: [
                         "Cookware",
                         "Cutlery",
                         "Dinnerware",
                         "Kitchen Appliances",
                         "Bakeware",
                         "Utensils",
                         "Glassware",
                         "Barware",
                         "Kitchen Tools",
                         "Food Storage",
                    ],
               },
               {
                    subCategoryName: "Appliances",
                    subSubCategories: [
                         "Refrigerators",
                         "Ovens",
                         "Dishwashers",
                         "Washers and Dryers",
                         "Microwaves",
                         "Coffee Makers",
                         "Blenders",
                         "Vacuum Cleaners",
                         "Air Purifiers",
                         "Irons",
                    ],
               },
               {
                    subCategoryName: "Outdoor Living",
                    subSubCategories: [
                         "Patio Furniture",
                         "Outdoor Decor",
                         "Grills and Accessories",
                         "Outdoor Lighting",
                         "Gardening",
                         "Pools and Spas",
                         "Outdoor Storage",
                         "Fencing",
                         "Outdoor Play",
                         "Sheds and Outdoor Structures",
                    ],
               },
               {
                    subCategoryName: "Home Improvement",
                    subSubCategories: [
                         "Tools",
                         "Paint and Supplies",
                         "Lighting Fixtures",
                         "Cabinets",
                         "Flooring",
                         "Doors and Windows",
                         "Roofing",
                         "Plumbing",
                         "Electrical",
                         "Hardware",
                    ],
               },
               {
                    subCategoryName: "Pet Supplies",
                    subSubCategories: [
                         "Dog Beds",
                         "Cat Furniture",
                         "Pet Food",
                         "Pet Toys",
                         "Collars and Leashes",
                         "Grooming Supplies",
                         "Aquariums",
                         "Bird Cages",
                         "Small Animal Habitats",
                         "Reptile Supplies",
                    ],
               },
               {
                    subCategoryName: "Cleaning Supplies",
                    subSubCategories: [
                         "Brooms and Mops",
                         "Vacuums",
                         "Cleaning Chemicals",
                         "Trash Bags",
                         "Laundry",
                         "Dishwashing",
                         "Storage and Organization",
                         "Air Fresheners",
                         "Paper Towels",
                         "Bathroom Cleaners",
                    ],
               },
               {
                    subCategoryName: "Home Electronics",
                    subSubCategories: [
                         "Smart Home Devices",
                         "Security Systems",
                         "Home Theater Systems",
                         "Cameras and Surveillance",
                         "Thermostats",
                         "Smart Lighting",
                         "Robot Vacuums",
                         "Audio Systems",
                         "Streaming Devices",
                         "Chargers and Power Strips",
                    ],
               },
          ],
     },
     {
          category: "Supermarkets",
          subcategories: [
               {
                    subCategoryName: "Fresh Produce",
                    subSubCategories: [
                         "Fruits",
                         "Vegetables",
                         "Herbs",
                         "Fresh Juices",
                         "Salads",
                         "Organic Produce",
                         "Berries",
                         "Exotic Fruits",
                         "Sprouts",
                         "Mushrooms",
                    ],
               },
               {
                    subCategoryName: "Dairy and Eggs",
                    subSubCategories: [
                         "Milk",
                         "Cheese",
                         "Yogurt",
                         "Butter",
                         "Eggs",
                         "Cream",
                         "Plant-Based Alternatives",
                         "Cottage Cheese",
                         "Sour Cream",
                         "Cheese Spreads",
                    ],
               },
               {
                    subCategoryName: "Bakery",
                    subSubCategories: [
                         "Bread",
                         "Pastries",
                         "Cakes",
                         "Cookies",
                         "Bagels",
                         "Muffins",
                         "Gluten-Free",
                         "Doughnuts",
                         "Pies",
                         "Rolls",
                    ],
               },
               {
                    subCategoryName: "Meat and Seafood",
                    subSubCategories: [
                         "Beef",
                         "Chicken",
                         "Pork",
                         "Lamb",
                         "Fish",
                         "Shrimp",
                         "Shellfish",
                         "Turkey",
                         "Sausages",
                         "Bacon",
                    ],
               },
               {
                    subCategoryName: "Frozen Foods",
                    subSubCategories: [
                         "Frozen Vegetables",
                         "Frozen Fruits",
                         "Frozen Meals",
                         "Ice Cream",
                         "Frozen Pizza",
                         "Frozen Snacks",
                         "Frozen Desserts",
                         "Frozen Seafood",
                         "Frozen Breakfast",
                         "Frozen Meat Alternatives",
                    ],
               },
               {
                    subCategoryName: "Canned Goods",
                    subSubCategories: [
                         "Canned Vegetables",
                         "Canned Fruits",
                         "Canned Beans",
                         "Canned Soup",
                         "Canned Meat",
                         "Canned Fish",
                         "Canned Tomatoes",
                         "Canned Pasta",
                         "Canned Sauce",
                         "Canned Chili",
                    ],
               },
               {
                    subCategoryName: "Pasta and Rice",
                    subSubCategories: [
                         "Pasta",
                         "Rice",
                         "Quinoa",
                         "Couscous",
                         "Noodles",
                         "Pasta Sauce",
                         "Risotto",
                         "Macaroni and Cheese",
                         "Pasta Alternatives",
                         "Instant Rice",
                    ],
               },
               {
                    subCategoryName: "Snacks and Chips",
                    subSubCategories: [
                         "Chips",
                         "Crackers",
                         "Popcorn",
                         "Pretzels",
                         "Nuts",
                         "Trail Mix",
                         "Granola Bars",
                         "Dried Fruit",
                         "Jerky",
                         "Seeds",
                    ],
               },
               {
                    subCategoryName: "Beverages",
                    subSubCategories: [
                         "Water",
                         "Soda",
                         "Juice",
                         "Coffee",
                         "Tea",
                         "Sports Drinks",
                         "Energy Drinks",
                         "Alcohol",
                         "Smoothies",
                         "Drink Mixes",
                    ],
               },
               {
                    subCategoryName: "Household Essentials",
                    subSubCategories: [
                         "Toilet Paper",
                         "Paper Towels",
                         "Cleaning Supplies",
                         "Laundry Detergent",
                         "Dish Soap",
                         "Trash Bags",
                         "Batteries",
                         "Light Bulbs",
                         "Air Fresheners",
                         "Kitchen Towels",
                    ],
               },
          ],
     },
     {
          category: "Beauty",
          subcategories: [
               {
                    subCategoryName: "Skincare",
                    subSubCategories: [
                         "Cleansers",
                         "Moisturizers",
                         "Serums",
                         "Masks",
                         "Exfoliators",
                         "Sunscreen",
                         "Tools",
                         "Toners",
                         "Eye Creams",
                         "Facial Oils",
                    ],
               },
               {
                    subCategoryName: "Haircare",
                    subSubCategories: [
                         "Shampoos",
                         "Conditioners",
                         "Styling Products",
                         "Hair Color",
                         "Hair Tools",
                         "Extensions",
                         "Accessories",
                         "Hair Masks",
                         "Hair Serums",
                         "Scalp Treatments",
                    ],
               },
               {
                    subCategoryName: "Makeup",
                    subSubCategories: [
                         "Lipstick",
                         "Eyeshadow",
                         "Foundation",
                         "Mascara",
                         "Blush",
                         "Makeup Brushes",
                         "Makeup Removers",
                         "Concealers",
                         "Setting Sprays",
                         "Eyeliners",
                    ],
               },
               {
                    subCategoryName: "Nail Care",
                    subSubCategories: [
                         "Nail Polish",
                         "Nail Polish Remover",
                         "Nail Tools",
                         "Nail Treatments",
                         "Nail Accessories",
                         "Gel Polish",
                         "Nail Art",
                         "Nail Extensions",
                         "Manicure Kits",
                         "Nail Strengtheners",
                    ],
               },
               {
                    subCategoryName: "Fragrance",
                    subSubCategories: [
                         "Perfume",
                         "Cologne",
                         "Body Mist",
                         "Roll-On Perfume",
                         "Perfume Sets",
                         "Home Fragrance",
                         "Scented Candles",
                         "Aromatherapy",
                         "Essential Oils",
                         "Diffusers",
                    ],
               },
               {
                    subCategoryName: "Bath and Body",
                    subSubCategories: [
                         "Body Wash",
                         "Body Lotion",
                         "Body Scrubs",
                         "Hand Cream",
                         "Shower Gel",
                         "Bath Salts",
                         "Body Butter",
                         "Deodorant",
                         "Massage Oils",
                         "Foot Care",
                    ],
               },
               {
                    subCategoryName: "Men's Grooming",
                    subSubCategories: [
                         "Shaving Cream",
                         "Aftershave",
                         "Beard Care",
                         "Men's Skincare",
                         "Hair Styling",
                         "Cologne for Men",
                         "Shampoo for Men",
                         "Body Wash for Men",
                         "Razors",
                         "Grooming Kits",
                    ],
               },
               {
                    subCategoryName: "Beauty Tools",
                    subSubCategories: [
                         "Makeup Brushes",
                         "Sponges",
                         "Mirrors",
                         "Hair Tools",
                         "Manicure Kits",
                         "Eyelash Curlers",
                         "Tweezers",
                         "Makeup Organizers",
                         "Shaving Tools",
                         "Face Rollers",
                    ],
               },
               {
                    subCategoryName: "Wellness",
                    subSubCategories: [
                         "Supplements",
                         "Essential Oils",
                         "Wellness Teas",
                         "Sleep Aids",
                         "Relaxation Tools",
                         "Fitness Supplements",
                         "Weight Management",
                         "Holistic Health",
                         "Meditation",
                         "Natural Remedies",
                    ],
               },
               {
                    subCategoryName: "Beauty Accessories",
                    subSubCategories: [
                         "Makeup Bags",
                         "Hair Accessories",
                         "Travel Sets",
                         "Compact Mirrors",
                         "Cosmetic Pouches",
                         "Beauty Blenders",
                         "Makeup Brush Holders",
                         "Jewelry Organizers",
                         "Tote Bags",
                         "Headbands",
                    ],
               },
          ],
     },
     {
          category: "Culture",
          subcategories: [
               {
                    subCategoryName: "Languages",
                    subSubCategories: [
                         "English",
                         "Spanish",
                         "Chinese",
                         "French",
                         "Arabic",
                         "Russian",
                         "Hindi",
                         "Portuguese",
                         "Japanese",
                         "German",
                    ],
               },
               {
                    subCategoryName: "Cuisine",
                    subSubCategories: [
                         "Italian",
                         "Japanese",
                         "Indian",
                         "Mexican",
                         "Chinese",
                         "Mediterranean",
                         "Thai",
                         "French",
                         "Brazilian",
                         "American",
                    ],
               },
               {
                    subCategoryName: "Art and Literature",
                    subSubCategories: [
                         "Visual Arts",
                         "Literature",
                         "Performing Arts",
                         "Music",
                         "Film",
                         "Poetry",
                         "Sculpture",
                         "Dance",
                         "Theater",
                         "Photography",
                    ],
               },
               {
                    subCategoryName: "History",
                    subSubCategories: [
                         "Ancient History",
                         "Medieval History",
                         "Modern History",
                         "World Wars",
                         "Renaissance",
                         "Colonial History",
                         "Cultural Revolutions",
                         "Historical Figures",
                         "Archaeology",
                         "Artifacts",
                    ],
               },
               {
                    subCategoryName: "Religion and Spirituality",
                    subSubCategories: [
                         "Christianity",
                         "Islam",
                         "Hinduism",
                         "Buddhism",
                         "Judaism",
                         "Sikhism",
                         "Taoism",
                         "Shamanism",
                         "New Age Spirituality",
                         "Atheism",
                    ],
               },
               {
                    subCategoryName: "Traditions and Customs",
                    subSubCategories: [
                         "Festivals",
                         "Ceremonies",
                         "Rituals",
                         "Cultural Practices",
                         "Customs",
                         "Celebrations",
                         "Cultural Symbols",
                         "Etiquette",
                         "Social Norms",
                         "Cultural Taboos",
                    ],
               },
               {
                    subCategoryName: "Travel and Exploration",
                    subSubCategories: [
                         "Historical Sites",
                         "Cultural Landmarks",
                         "Museums",
                         "Heritage Tours",
                         "Cultural Experiences",
                         "Culinary Tourism",
                         "Ethnic Enclaves",
                         "Pilgrimages",
                         "Festivals Abroad",
                         "Cultural Festivals",
                    ],
               },
               {
                    subCategoryName: "Pop Culture",
                    subSubCategories: [
                         "Music Trends",
                         "Film and TV Shows",
                         "Celebrities",
                         "Internet Culture",
                         "Social Media Trends",
                         "Fashion Trends",
                         "Slang and Jargon",
                         "Cultural Phenomena",
                         "Fan Communities",
                         "Memorabilia",
                    ],
               },
               {
                    subCategoryName: "Education and Learning",
                    subSubCategories: [
                         "Liberal Arts",
                         "Cultural Studies",
                         "Anthropology",
                         "Sociology",
                         "Philosophy",
                         "Ethics",
                         "Comparative Literature",
                         "Languages and Linguistics",
                         "Cultural Anthropology",
                         "Archaeology",
                    ],
               },
               {
                    subCategoryName: "Sports and Games",
                    subSubCategories: [
                         "Traditional Sports",
                         "Sports Events",
                         "E-sports",
                         "Board Games",
                         "Card Games",
                         "Chess",
                         "Video Games",
                         "Cultural Impact of Sports",
                         "Olympic Games",
                         "Cultural Games",
                    ],
               },
          ],
     },
     {
          category: "Sports & Tourism",
          subcategories: [
               {
                    subCategoryName: "Sports",
                    subSubCategories: ["Basketball", "Soccer", "Baseball", "Tennis", "Golf"],
               },
               {
                    subCategoryName: "Adventure Sports",
                    subSubCategories: ["Hiking", "Rock Climbing", "Surfing", "Skiing", "Skydiving"],
               },
               {
                    subCategoryName: "Water Sports",
                    subSubCategories: ["Swimming", "Snorkeling", "Kayaking", "Scuba Diving", "Water Skiing"],
               },
               {
                    subCategoryName: "Cultural Tourism",
                    subSubCategories: [
                         "Historical Sites",
                         "Museums",
                         "Cultural Events",
                         "Heritage Tours",
                         "Art Exhibitions",
                    ],
               },
               {
                    subCategoryName: "Eco Tourism",
                    subSubCategories: [
                         "National Parks",
                         "Wildlife Sanctuaries",
                         "Nature Trails",
                         "Sustainable Tours",
                         "Bird Watching",
                    ],
               },
               {
                    subCategoryName: "Sports Events",
                    subSubCategories: [
                         "Olympic Games",
                         "World Cup",
                         "Super Bowl",
                         "Grand Slam Tournaments",
                         "Tour de France",
                    ],
               },
               {
                    subCategoryName: "Outdoor Adventure",
                    subSubCategories: ["Camping", "Backpacking", "Mountain Biking", "Zip Lining", "Outdoor Survival"],
               },
               {
                    subCategoryName: "Beach Tourism",
                    subSubCategories: [
                         "Tropical Beaches",
                         "Island Getaways",
                         "Beach Resorts",
                         "Beach Activities",
                         "Coastal Tours",
                    ],
               },
               {
                    subCategoryName: "Culinary Tourism",
                    subSubCategories: [
                         "Food Festivals",
                         "Wine Tours",
                         "Gastronomic Tours",
                         "Culinary Classes",
                         "Local Cuisine Exploration",
                    ],
               },
               {
                    subCategoryName: "Winter Sports",
                    subSubCategories: ["Skiing", "Snowboarding", "Ice Skating", "Winter Festivals", "Ice Fishing"],
               },
          ],
     },
     {
          category: "Automotive",
          subcategories: [
               {
                    subCategoryName: "Cars",
                    subSubCategories: ["Sedans", "SUVs", "Trucks", "Coupes", "Hatchbacks"],
               },
               {
                    subCategoryName: "Motorcycles",
                    subSubCategories: ["Cruisers", "Sport Bikes", "Touring Bikes", "Dirt Bikes", "Scooters"],
               },
               {
                    subCategoryName: "Electric Vehicles",
                    subSubCategories: [
                         "Electric Cars",
                         "Electric Bikes",
                         "Electric Scooters",
                         "Hybrid Vehicles",
                         "Electric Trucks",
                    ],
               },
               {
                    subCategoryName: "Parts and Accessories",
                    subSubCategories: ["Tires", "Batteries", "Brake Pads", "Oil Filters", "Exhaust Systems"],
               },
               {
                    subCategoryName: "Car Care and Maintenance",
                    subSubCategories: ["Car Cleaning", "Oil Change", "Tire Care", "Car Batteries", "Car Tools"],
               },
               {
                    subCategoryName: "Off-Road Vehicles",
                    subSubCategories: ["ATVs", "Off-Road Trucks", "Dirt Bikes", "UTVs", "Motocross Bikes"],
               },
               {
                    subCategoryName: "Car Electronics",
                    subSubCategories: ["Car Audio", "GPS Navigation", "Dash Cams", "Car Alarms", "Bluetooth Car Kits"],
               },
               {
                    subCategoryName: "Classic Cars",
                    subSubCategories: [
                         "Vintage Cars",
                         "Classic Trucks",
                         "Antique Cars",
                         "Restoration Projects",
                         "Classic Car Parts",
                    ],
               },
               {
                    subCategoryName: "Car Insurance and Finance",
                    subSubCategories: [
                         "Auto Insurance",
                         "Car Loans",
                         "Leasing",
                         "Car Financing",
                         "Insurance Providers",
                    ],
               },
               {
                    subCategoryName: "Car Brands",
                    subSubCategories: ["Toyota", "Ford", "Chevrolet", "Honda", "BMW"],
               },
          ],
     },
     {
          category: "Digital",
          subcategories: [
               {
                    subCategoryName: "Smartphones and Accessories",
                    subSubCategories: [
                         "Smartphones",
                         "Phone Cases",
                         "Screen Protectors",
                         "Chargers",
                         "Bluetooth Headsets",
                    ],
               },
               {
                    subCategoryName: "Computers and Laptops",
                    subSubCategories: ["Laptops", "Desktop Computers", "Computer Accessories", "Monitors", "Printers"],
               },
               {
                    subCategoryName: "Audio and Headphones",
                    subSubCategories: ["Headphones", "Earbuds", "Speakers", "Soundbars", "Audio Accessories"],
               },
               {
                    subCategoryName: "Cameras and Photography",
                    subSubCategories: [
                         "Digital Cameras",
                         "DSLR Cameras",
                         "Mirrorless Cameras",
                         "Camera Lenses",
                         "Camera Accessories",
                    ],
               },
               {
                    subCategoryName: "Wearables",
                    subSubCategories: [
                         "Smartwatches",
                         "Fitness Trackers",
                         "VR Headsets",
                         "Health Monitors",
                         "Wearable Accessories",
                    ],
               },
               {
                    subCategoryName: "Gaming",
                    subSubCategories: [
                         "Gaming Consoles",
                         "Video Games",
                         "Gaming Accessories",
                         "Gaming Laptops",
                         "Gaming Peripherals",
                    ],
               },
               {
                    subCategoryName: "Software and Apps",
                    subSubCategories: [
                         "Operating Systems",
                         "Productivity Software",
                         "Antivirus Software",
                         "Mobile Apps",
                         "Gaming Apps",
                    ],
               },
               {
                    subCategoryName: "Home Electronics",
                    subSubCategories: [
                         "Smart Home Devices",
                         "Security Systems",
                         "Home Theater Systems",
                         "Cameras and Surveillance",
                         "Smart Lighting",
                    ],
               },
               {
                    subCategoryName: "Networking and Internet",
                    subSubCategories: [
                         "Routers",
                         "Modems",
                         "Network Switches",
                         "Wi-Fi Extenders",
                         "Cables and Connectors",
                    ],
               },
               {
                    subCategoryName: "Tech Gadgets",
                    subSubCategories: ["Drones", "Smart Mirrors", "Virtual Assistants", "Robot Vacuums", "Tech Toys"],
               },
          ],
     },
];
